services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-tiktok
    ports:
      - "8080:8080"
    restart: unless-stopped
    privileged: true
    environment:
      - SERVER_PORT=8081
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro   