services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-tiktok
    ports:
      - "8081:8081"
    restart: unless-stopped
    privileged: true
    environment:
      - SERVER_PORT=8081
      - TZ=Asia/Ho_Chi_Minh  # ⭐ Thêm múi giờ Việt Nam
    volumes:
      - /etc/localtime:/etc/localtime:ro  # ⭐ Đồng bộ thời gian từ host
      - /etc/timezone:/etc/timezone:ro    # ⭐ Đồng bộ timezone từ host